version: '3.8'

services:
  node_backend:
    container_name: node_tabnine
    image: node_tabnine:0.0.2
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - EXTERNAL_PORT=3001
    depends_on:
    - node_db 
  node_db:
    container_name: node_db
    image: "postgres:12"
    ports: 
    - "3001:3001"
    environment:
      -POSTGRES_USER
      -POSTGRES_PASSWORD
